version: '3.8'

services:
  app:
    container_name: chatgpt-api-app
    build:
      context: .
      dockerfile: ./docker/prod/app/Dockerfile
    image: chatgpt-api-app:latest
    restart: always
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_KEY: ${APP_KEY}

  nginx:
    container_name: chatgpt-api-nginx
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app
